apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonLabels:
  environment: prod

images:
- name: my-repo/backend
  newTag: prod-latest
- name: my-repo/frontend
  newTag: prod-latest
