apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonLabels:
  environment: prod

images:
- name: my-repo/delivery-service
  newName: 381492025532.dkr.ecr.us-east-1.amazonaws.com/prod-delivery
  newTag: 87f12c3430bd841b182a343233a89996876afce8
- name: my-repo/frontend
  newName: 381492025532.dkr.ecr.us-east-1.amazonaws.com/prod-frontend
  newTag: 87f12c3430bd841b182a343233a89996876afce8
- name: my-repo/notifications-service
  newName: 381492025532.dkr.ecr.us-east-1.amazonaws.com/prod-notifications
  newTag: 87f12c3430bd841b182a343233a89996876afce8
- name: my-repo/orders-service
  newName: 381492025532.dkr.ecr.us-east-1.amazonaws.com/prod-orders
  newTag: 87f12c3430bd841b182a343233a89996876afce8
- name: my-repo/payments-service
  newName: 381492025532.dkr.ecr.us-east-1.amazonaws.com/prod-payments
  newTag: 87f12c3430bd841b182a343233a89996876afce8

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "REPLACE_WITH_PROD_KAFKA_BROKERS"
  target:
    kind: Deployment
    name: .*-service
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value
      value: "REPLACE_WITH_PROD_KAFKA_BROKERS"
  target:
    kind: Job
    name: kafka-setup
