apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonLabels:
  environment: prod

images:
- name: my-repo/orders-service
  newTag: prod-latest
- name: my-repo/payments-service
  newTag: prod-latest
- name: my-repo/delivery-service
  newTag: prod-latest
- name: my-repo/notifications-service
  newTag: prod-latest
- name: my-repo/frontend
  newTag: prod-latest
