apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: observability
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-admin
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        admin-user: "admin"
        admin-password: "{{ .adminPassword }}"
  data:
  - secretKey: adminPassword
    remoteRef:
      key: secret/data/grafana
      property: admin-password
