server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy /orders/ to orders-service
    location /orders/ {
        proxy_pass http://orders-service.default.svc.cluster.local:8001/orders/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy /payments/ to payments-service
    location /payments/ {
        proxy_pass http://payments-service.default.svc.cluster.local:8002/payments/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy /notifications/ to notifications-service
    location /notifications/ {
        proxy_pass http://notifications-service.default.svc.cluster.local:8003/notifications/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy /delivery/ to delivery-service
    location /delivery/ {
        proxy_pass http://delivery-service.default.svc.cluster.local:8005/delivery/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
