apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  namespace: default
  labels:
    app: delivery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: my-repo/delivery-service:latest
          ports:
            - containerPort: 8005
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "b-1.devkafka.bikqyw.c6.kafka.us-east-1.amazonaws.com:9092,b-2.devkafka.bikqyw.c6.kafka.us-east-1.amazonaws.com:9092"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
