apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - delivery-deployment.yaml
  - delivery-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - notifications-deployment.yaml
  - notifications-service.yaml
  - orders-deployment.yaml
  - orders-service.yaml
  - payments-deployment.yaml
  - payments-service.yaml
  - kafka-setup-job.yaml
