name: Prod Workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_PROD }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Backend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: prod-backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd microservice-app/backend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Build and Push Frontend
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: prod-frontend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd microservice-app/frontend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update K8s Manifests
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd k8s/overlays/prod
          kustomize edit set image my-repo/backend=$ECR_REGISTRY/prod-backend:${{ github.sha }}
          kustomize edit set image my-repo/frontend=$ECR_REGISTRY/prod-frontend:${{ github.sha }}

      - name: Commit and Push
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add k8s/overlays/prod/kustomization.yaml
          git commit -m "Update image tags to ${{ github.sha }}"
          git push origin main
