apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonLabels:
  environment: staging

images:
- name: my-repo/orders-service
  newTag: staging-latest
- name: my-repo/payments-service
  newTag: staging-latest
- name: my-repo/delivery-service
  newTag: staging-latest
- name: my-repo/notifications-service
  newTag: staging-latest
- name: my-repo/frontend
  newTag: staging-latest

patches:
  - target:
      kind: Deployment
      name: ".*-service"
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "REPLACE_WITH_STAGING_KAFKA_BROKERS"
  - target:
      kind: Job
      name: kafka-setup
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "REPLACE_WITH_STAGING_KAFKA_BROKERS"
